# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of your requirements.txt
    schedule:
      interval: "weekly"  # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-type: "direct"  # Only update direct dependencies (you can add indirect too)
    ignore:
      - dependency-name: "pywhatkit"
        versions: ["<5.0.0"]  # Example: ignore pywhatkit below 5.0.0 (optional)

