name: Send WhatsApp Message via pywhatkit to any mobile number

on:
  workflow_dispatch:  # manual trigger from GitHub Actions UI

jobs:
  send-message:
    runs-on: self-hosted  # runs on your local self-hosted runner (with GUI)

    env:
      PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Confirm Python Version Used
      run: python --version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run WhatsApp Message Script
      run: |
        python send_message.py
